import GlobalStyle from "@/styles/globalStyles";

export const metadata = {
  title: 'tractian code challenge',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyle />
      <body>{children}</body>
    </html>
  )
}
